services:
  - type: web
    name: gestion-de-conges
    env: php
    plan: free
    region: oregon
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
